### ISSUE TITLE
Merging the Python CAN viewer tool into the python-can library

### ISSUE THREAD

**Issue by felixdivo** [Lauszus/python_can_viewer#2]
I have just read the README of your library, and think that it would be a nice addition to [python-can](https://github.com/hardbyte/python-can)'s already existing [Scripts](https://python-can.readthedocs.io/en/stable/bin.html). We could in theory move your tool together with the two that are already there, and put them in a distinct `scripts/` folder or something. That should be done anyways.  We would then of course copy the documentation over as well.

BTW: Impressive 100% code coverage (although the code isn't huge, still nice)! 👍 

How do you feel about this?

**Comment by Lauszus** [comment]
That would be great :) I'm in the middle of putting the code into a class, so I don't have to parse all the variables around.

It would also be great if we could add a short section covering the scripts in the main Readme, as I actually never knew they even existed before I started writing this script. 

I have actually cheated a bit with the coverage, as I have disabled it for the main while loop, but I have also fixed this by mocking curses. I will push it in a few days when I have tested it properly.

**Comment by felixdivo** [comment]
Okay nice, that sounds great! I will have a look at the python-can script's in the meantime. 

@hardbyte FYI

**Comment by felixdivo** [comment]
Your code is currently licensed as GPL v2.0, but python-can uses LGPL 3.0. This shouldn't be a huge issue, just for you to take notice.

**Comment by Lauszus** [comment]
No worries about the license, I'm happy to change it.

**Comment by felixdivo** [comment]
The [Readme of the python-can libarary](https://github.com/hardbyte/python-can#features) now includes this:

> CLI tools for working with CAN busses (see the *docs*)

**Comment by Lauszus** [comment]
@felixdivo thanks! I'll send you a PR soon then :)

**Comment by felixdivo** [comment]
This has been merged in hardbyte/python-can#390. 🎉

**Comment by Lauszus** [comment]
@felixdivo awesome :)
